name: Build ARM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-arm:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: uraimo/run-on-arch-action@v2.3.0
        with: 
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update && apt-get upgrade -y && apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
          run: |
            source "$HOME/.cargo/env"
            cargo build --release
            ls -la target/release
